/**
 * User API Endpoints
 * user api endpoints
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { User } from './user';


export interface GetAllResponse { 
    users: Array<User>;
    total_records: number;
    total_pages: number;
}

