/**
 * User API Endpoints
 * user api endpoints
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface User { 
    user_id?: number;
    active?: boolean;
    email?: string;
    require_new_password?: string;
    name?: string;
    first_name?: string;
    last_name?: string;
    a1?: string;
    a2?: string;
    a3?: string;
    q1?: string;
    q2?: string;
    q3?: string;
    reset_code?: string;
    reset_exp?: string;
    last_access?: string;
    login_access?: string;
    updt_id?: number;
    language_id?: number;
}

